swagger: "2.0"
info:
  title: Employee Management System
  description: Demo API specs for Tech Council
  contact:
    name: eGov Foundation
    url: https://core.digit.org
  version: 1.0.0
paths:
  /employee/_create:
    post:
      summary: Operation to create a new employee
      description: |
        To create new employee in the system.
      parameters:
        - name: EmployeeRequest
          in: body
          description: Details for the new employee.
          required: true
          schema:
            $ref: '#/definitions/EmployeeRequest'
      responses:
        '201':
          description: ReponseInfo with Voter Registration Application(s) created successfully
        '400':
          description: Voter Registration Application(s) creation failed
definitions:
  EmployeeRequest:
    type: object
    properties:
      employeeId:
        type: integer
        example: 3
      name:
        type: string
        example: Ramesh
